name: cybershamanka
favicon: null
layout_spectrum: 0.6079610935412347
typography_spectrum: 0.4990866610314697
title: cybershamanka agata_dreams
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#42e800'
    - '#002bfe'
    - '#c000fe'
    - '#00b1fe'
    - '#f84705'
  brandStrength: 0.6602964343037456
  lightness: 0.23053994518704712
  saturation: 0.633694947231561
  rhythmicContrast: 0.35441386536695063
purpose: []
